#!/usr/bin/env python3
"""
Lib to build the hybrid-Cartesian ArmCartesianCommand for one push.
"""
from __future__ import annotations  # for 'Vec3 | None' python3.8

import numpy as np
from scipy.spatial.transform import Rotation
from bosdyn.client.frame_helpers import ODOM_FRAME_NAME, VISION_FRAME_NAME
from bosdyn.api import (arm_command_pb2, geometry_pb2, trajectory_pb2,
                        synchronized_command_pb2, robot_command_pb2,
                        basic_command_pb2, mobility_command_pb2, geometry_pb2)
from bosdyn.util import seconds_to_duration

# Fallback only, executor node overrides this value to appropriate one.
FORCE_NORM_CLIP = 85.0


def rotmat_to_quat_wxyz(R):
    x, y, z, w = Rotation.from_matrix(R).as_quat()
    return np.array([w, x, y, z])


def task_frame_from_force(push_force):
    """
    Return (magnitude, quat_wxyz) for a task frame whose x-axis = push dir.
    """
    f = np.asarray(push_force, dtype=np.float64)
    mag = float(np.linalg.norm(f))
    if mag < 1e-9:
        return 0.0, np.array([1.0, 0.0, 0.0, 0.0])
    x = f / mag
    up = np.array([0.0, 0.0, 1.0]) if abs(x[2]) < 0.95 else np.array([1.0, 0.0, 0.0])
    y = np.cross(up, x)
    y /= np.linalg.norm(y)
    z = np.cross(x, y)
    R = np.column_stack([x, y, z])
    return mag, rotmat_to_quat_wxyz(R)


def build_arm_cartesian_command(contact_point, push_force, root_frame=ODOM_FRAME_NAME,
                                duration_s=1.5, force_clip=FORCE_NORM_CLIP,
                                follow_arm=False):
    """
    Force mode that pushes along the given direction (task frame x axis), with lateral + rotational axes in position mode.
    Return (RobotCommand proto, magnitude, task_quat_wxyz).
    """

    mag, q = task_frame_from_force(push_force)
    mag = min(mag, force_clip)
    cp = [float(v) for v in contact_point]
    Req = arm_command_pb2.ArmCartesianCommand.Request

    identity = geometry_pb2.SE3Pose(
        position=geometry_pb2.Vec3(x=0.0, y=0.0, z=0.0),
        rotation=geometry_pb2.Quaternion(w=1.0, x=0.0, y=0.0, z=0.0))
    root_tform_task = geometry_pb2.SE3Pose(
        position=geometry_pb2.Vec3(x=cp[0], y=cp[1], z=cp[2]),
        rotation=geometry_pb2.Quaternion(w=q[0], x=q[1], y=q[2], z=q[3]))

    pose_traj = trajectory_pb2.SE3Trajectory(points=[trajectory_pb2.SE3TrajectoryPoint(
        pose=identity, time_since_reference=seconds_to_duration(duration_s))])
    wrench_traj = trajectory_pb2.WrenchTrajectory(points=[trajectory_pb2.WrenchTrajectoryPoint(
        wrench=geometry_pb2.Wrench(force=geometry_pb2.Vec3(x=mag, y=0.0, z=0.0),
                                   torque=geometry_pb2.Vec3(x=0.0, y=0.0, z=0.0)),
        time_since_reference=seconds_to_duration(duration_s))])

    req = Req(
        root_frame_name=root_frame,
        root_tform_task=root_tform_task,
        wrist_tform_tool=identity,
        pose_trajectory_in_task=pose_traj,
        wrench_trajectory_in_task=wrench_traj,
        x_axis=Req.AXIS_MODE_FORCE,
        y_axis=Req.AXIS_MODE_POSITION,
        z_axis=Req.AXIS_MODE_POSITION,
        # Roll about the push axis (task-x) is in force mode with zero torque 
        # (to keep it compliant) so the arm never exessively moves the wrist to match 
        # the random roll generated by gram-schmidt.
        rx_axis=Req.AXIS_MODE_FORCE,
        ry_axis=Req.AXIS_MODE_POSITION,
        rz_axis=Req.AXIS_MODE_POSITION,
    )
    arm_cmd = arm_command_pb2.ArmCommand.Request(arm_cartesian_command=req)
    if follow_arm:
        sync = synchronized_command_pb2.SynchronizedCommand.Request(
            arm_command=arm_cmd, mobility_command=build_follow_arm_command())
    else:
        sync = synchronized_command_pb2.SynchronizedCommand.Request(arm_command=arm_cmd)
    cmd = robot_command_pb2.RobotCommand(synchronized_command=sync)
    return cmd, mag, q


def build_standoff_pose_command(contact_point, push_dir, quat_wxyz, root_frame=ODOM_FRAME_NAME,
                                eps=0.10, duration_s=2.0, follow_arm=False):
    """
    Position-mode move that aligns the hand on the push axis before contact.
    follow_arm=True allows the base tracks the arm

    Returns (RobotCommand proto, standoff_point).
    """
    push_dir = np.asarray(push_dir, dtype=np.float64)
    n = np.linalg.norm(push_dir)
    if n > 1e-9:
        push_dir = push_dir / n
    standoff = np.asarray(contact_point, dtype=np.float64) - eps * push_dir
    sp = [float(v) for v in standoff]
    q = quat_wxyz
    Req = arm_command_pb2.ArmCartesianCommand.Request

    identity = geometry_pb2.SE3Pose(
        position=geometry_pb2.Vec3(x=0.0, y=0.0, z=0.0),
        rotation=geometry_pb2.Quaternion(w=1.0, x=0.0, y=0.0, z=0.0))
    root_tform_task = geometry_pb2.SE3Pose(
        position=geometry_pb2.Vec3(x=sp[0], y=sp[1], z=sp[2]),
        rotation=geometry_pb2.Quaternion(w=q[0], x=q[1], y=q[2], z=q[3]))
    pose_traj = trajectory_pb2.SE3Trajectory(points=[trajectory_pb2.SE3TrajectoryPoint(
        pose=identity, time_since_reference=seconds_to_duration(duration_s))])

    req = Req(
        root_frame_name=root_frame,
        root_tform_task=root_tform_task,
        wrist_tform_tool=identity,
        pose_trajectory_in_task=pose_traj,
        x_axis=Req.AXIS_MODE_POSITION,
        y_axis=Req.AXIS_MODE_POSITION,
        z_axis=Req.AXIS_MODE_POSITION,
        rx_axis=Req.AXIS_MODE_POSITION,
        ry_axis=Req.AXIS_MODE_POSITION,
        rz_axis=Req.AXIS_MODE_POSITION,
    )
    arm_cmd = arm_command_pb2.ArmCommand.Request(arm_cartesian_command=req)
    if follow_arm:
        sync = synchronized_command_pb2.SynchronizedCommand.Request(
            arm_command=arm_cmd, mobility_command=build_follow_arm_command())
    else:
        sync = synchronized_command_pb2.SynchronizedCommand.Request(arm_command=arm_cmd)
    cmd = robot_command_pb2.RobotCommand(synchronized_command=sync)
    return cmd, standoff


def world_contact_from_object(R_root_obj, t_root_obj, push_point, force_body):
    """
    Transform the contact point and force vector from the object frame to the world frame.
    Returns (contact_world, force_world) as 3-vectors.
    """
    R = np.asarray(R_root_obj, dtype=np.float64)
    t = np.asarray(t_root_obj, dtype=np.float64)
    contact_world = R @ np.asarray(push_point, dtype=np.float64) + t
    force_world = R @ np.asarray(force_body, dtype=np.float64)
    return contact_world, force_world


def build_follow_arm_command(body_offset_from_hand: geometry_pb2.Vec3 | None = None):
    if body_offset_from_hand is None:
        mobility_cmd = mobility_command_pb2.MobilityCommand.Request(
                        follow_arm_request=basic_command_pb2.FollowArmCommand.Request())
    else:
        mobility_cmd = mobility_command_pb2.MobilityCommand.Request(
                        follow_arm_request=basic_command_pb2.FollowArmCommand.Request(
                            body_offset_from_hand=body_offset_from_hand))
    return mobility_cmd